/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ChangeDetails {
  message: string
  description?: string
  timestamp: string
  authors: Array<string>
  hunks: Array<HunkDetails>
}

export interface DiffLine {
  lineNumber: number
  content: string
  lineType: string
}

/** A single file or directory entry returned by [`list_files`]. */
export interface FileEntry {
  /** Repository-relative path using `/` as separator, e.g. `"src/main.rs"`. */
  path: string
  /** `true` when this entry is a directory. */
  isDir: boolean
}

/**
 * High-level API: Get details and hunks of a specific change (patch).
 *
 * Returns a `ChangeDetails` struct containing metadata and a list of hunks.
 */
export declare function getChangeDetails(repoPath: string, changeHash: string, channelName?: string | undefined | null): ChangeDetails

/**
 * High-level API: Read the raw byte content of a specific file in a channel.
 *
 * Returns a `Buffer` containing the file contents (including any conflict markers).
 */
export declare function getFileContent(repoPath: string, channelName: string | undefined | null, filePath: string): Buffer

/**
 * High-level API: List files in a Pijul repository for a given channel and path prefix.
 *
 * Returns a list of `FileEntry` structs.
 */
export declare function getRepositoryFiles(repoPath: string, channelName: string | undefined | null, pathPrefix: string): Array<FileEntry>

export interface HunkDetails {
  hunkType: string
  path: string
  line?: number
  contents?: Buffer
  replacementContents?: Buffer
  newPath?: string
  lines: Array<DiffLine>
  oldData?: string
  newData?: string
  previous?: string
  remove?: string
}
